#include <stdio.h>
#include "hocdec.h"
extern int nrnmpi_myid;
extern int nrn_nobanner_;

extern void _BAer2CeLPKCDm_reg(void);
extern void _BAer2CeLPKCDp_reg(void);
extern void _BAer2CeM_reg(void);
extern void _BAf2CeLPKCDm_reg(void);
extern void _BAf2CeLPKCDp_reg(void);
extern void _BAf2CeM_reg(void);
extern void _BAnor2CeLPKCDm_reg(void);
extern void _BAnor2CeLPKCDp_reg(void);
extern void _BAnor2CeM_reg(void);
extern void _CE_cal_reg(void);
extern void _CE_capool_reg(void);
extern void _CE_cat_reg(void);
extern void _CE_ia_reg(void);
extern void _CE_ih_reg(void);
extern void _CE_Ihva_reg(void);
extern void _CE_im_reg(void);
extern void _CE_kdr_reg(void);
extern void _CE_leak_reg(void);
extern void _CeLPKCDm2CeLPKCDm_reg(void);
extern void _CeLPKCDm2CeLPKCDp_reg(void);
extern void _CeLPKCDm2CeM_reg(void);
extern void _CeLPKCDp2CeLPKCDm_reg(void);
extern void _CeLPKCDp2CeLPKCDp_reg(void);
extern void _CeLPKCDp2CeM_reg(void);
extern void _CeM2CeM_reg(void);
extern void _CE_na_reg(void);
extern void _CE_sahp_reg(void);
extern void _currentclamp_reg(void);
extern void _function_TMonitor_reg(void);
extern void _ITCd2CeLPKCDm_reg(void);
extern void _ITCd2CeLPKCDp_reg(void);
extern void _ITCv2CeM_reg(void);
extern void _LAer2CeLPKCDm_reg(void);
extern void _LAer2CeLPKCDp_reg(void);
extern void _LAer2CeM_reg(void);
extern void _LAf2CeLPKCDm_reg(void);
extern void _LAf2CeLPKCDp_reg(void);
extern void _LAf2CeM_reg(void);
extern void _LAnor2CeLPKCDm_reg(void);
extern void _LAnor2CeLPKCDp_reg(void);
extern void _LAnor2CeM_reg(void);
extern void _PVT2CeLPKCDm_reg(void);
extern void _PVT2CeLPKCDp_reg(void);
extern void _shock_reg(void);

void modl_reg(){
  if (!nrn_nobanner_) if (nrnmpi_myid < 1) {
    fprintf(stderr, "Additional mechanisms from files\n");

    fprintf(stderr," BAer2CeLPKCDm.mod");
    fprintf(stderr," BAer2CeLPKCDp.mod");
    fprintf(stderr," BAer2CeM.mod");
    fprintf(stderr," BAf2CeLPKCDm.mod");
    fprintf(stderr," BAf2CeLPKCDp.mod");
    fprintf(stderr," BAf2CeM.mod");
    fprintf(stderr," BAnor2CeLPKCDm.mod");
    fprintf(stderr," BAnor2CeLPKCDp.mod");
    fprintf(stderr," BAnor2CeM.mod");
    fprintf(stderr," CE_cal.mod");
    fprintf(stderr," CE_capool.mod");
    fprintf(stderr," CE_cat.mod");
    fprintf(stderr," CE_ia.mod");
    fprintf(stderr," CE_ih.mod");
    fprintf(stderr," CE_Ihva.mod");
    fprintf(stderr," CE_im.mod");
    fprintf(stderr," CE_kdr.mod");
    fprintf(stderr," CE_leak.mod");
    fprintf(stderr," CeLPKCDm2CeLPKCDm.mod");
    fprintf(stderr," CeLPKCDm2CeLPKCDp.mod");
    fprintf(stderr," CeLPKCDm2CeM.mod");
    fprintf(stderr," CeLPKCDp2CeLPKCDm.mod");
    fprintf(stderr," CeLPKCDp2CeLPKCDp.mod");
    fprintf(stderr," CeLPKCDp2CeM.mod");
    fprintf(stderr," CeM2CeM.mod");
    fprintf(stderr," CE_na.mod");
    fprintf(stderr," CE_sahp.mod");
    fprintf(stderr," currentclamp.mod");
    fprintf(stderr," function_TMonitor.mod");
    fprintf(stderr," ITCd2CeLPKCDm.mod");
    fprintf(stderr," ITCd2CeLPKCDp.mod");
    fprintf(stderr," ITCv2CeM.mod");
    fprintf(stderr," LAer2CeLPKCDm.mod");
    fprintf(stderr," LAer2CeLPKCDp.mod");
    fprintf(stderr," LAer2CeM.mod");
    fprintf(stderr," LAf2CeLPKCDm.mod");
    fprintf(stderr," LAf2CeLPKCDp.mod");
    fprintf(stderr," LAf2CeM.mod");
    fprintf(stderr," LAnor2CeLPKCDm.mod");
    fprintf(stderr," LAnor2CeLPKCDp.mod");
    fprintf(stderr," LAnor2CeM.mod");
    fprintf(stderr," PVT2CeLPKCDm.mod");
    fprintf(stderr," PVT2CeLPKCDp.mod");
    fprintf(stderr," shock.mod");
    fprintf(stderr, "\n");
  }
  _BAer2CeLPKCDm_reg();
  _BAer2CeLPKCDp_reg();
  _BAer2CeM_reg();
  _BAf2CeLPKCDm_reg();
  _BAf2CeLPKCDp_reg();
  _BAf2CeM_reg();
  _BAnor2CeLPKCDm_reg();
  _BAnor2CeLPKCDp_reg();
  _BAnor2CeM_reg();
  _CE_cal_reg();
  _CE_capool_reg();
  _CE_cat_reg();
  _CE_ia_reg();
  _CE_ih_reg();
  _CE_Ihva_reg();
  _CE_im_reg();
  _CE_kdr_reg();
  _CE_leak_reg();
  _CeLPKCDm2CeLPKCDm_reg();
  _CeLPKCDm2CeLPKCDp_reg();
  _CeLPKCDm2CeM_reg();
  _CeLPKCDp2CeLPKCDm_reg();
  _CeLPKCDp2CeLPKCDp_reg();
  _CeLPKCDp2CeM_reg();
  _CeM2CeM_reg();
  _CE_na_reg();
  _CE_sahp_reg();
  _currentclamp_reg();
  _function_TMonitor_reg();
  _ITCd2CeLPKCDm_reg();
  _ITCd2CeLPKCDp_reg();
  _ITCv2CeM_reg();
  _LAer2CeLPKCDm_reg();
  _LAer2CeLPKCDp_reg();
  _LAer2CeM_reg();
  _LAf2CeLPKCDm_reg();
  _LAf2CeLPKCDp_reg();
  _LAf2CeM_reg();
  _LAnor2CeLPKCDm_reg();
  _LAnor2CeLPKCDp_reg();
  _LAnor2CeM_reg();
  _PVT2CeLPKCDm_reg();
  _PVT2CeLPKCDp_reg();
  _shock_reg();
}
