#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/gpfs/homeb/pcp0/pcp0129/neuron_install/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/gpfs/homeb/pcp0/pcp0129/neuron_install/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/gpfs/work/pcp0/pcp0129/Ce_HOC/Scripts_NEURON/x86_64/.libs/libnrnmech.so" "$@"
